# Generated by Django 6.0.1 on 2026-01-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_total_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retal_period',
            new_name='rental_period',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='retal_price_day',
            new_name='rental_price_day',
        ),
    ]
